### PR TITLE
Add WebServer Framework and c++ compilation tools

### PR DESCRIPTION
**Pull request by bokket**
Signed-off-by: bokket <3100563328@qq.com>
Fix:#1

### CODE REVIEW

**Review by Y7n05h — CHANGES_REQUESTED** [review]
I think it might be more appropriate to put relevant content of the build tool on a separate page.

**Comment by bokket** [comment]
> I think it might be more appropriate to put relevant content of the build tool on a separate page.

fix

**Comment by adlternative** [comment]
Welcome, bokket,
Well, I don't think it's necessary to talk with English...
It will add our communicate burden.

**Comment by adlternative** [comment]
By the way, you can add Distributed-System informations to
`Distributed.md` from ZhaoLong Li . This is an important content
that we still lack, it will be helpful for us.

Thanks.

**Comment by Y7n05h** [comment]
> Welcome, bokket,
> Well, I don't think it's necessary to talk with English...
> It will add our communicate burden.

But you still ues English...

**Comment by Y7n05h** [comment]
请将新的页面添加进 README.md。
新的页面应当采用 大驼峰命名规则（upper camel case） 以便与已有页面保持一致。
感谢你为此项目的付出。

**Comment by bokket** [comment]
> 请将新的页面添加进 README.md。
> 新的页面应当采用 大驼峰命名规则（upper camel case） 以便与已有页面保持一致。
> 感谢你为此项目的付出。

done

**Comment by bokket** [comment]
> By the way, you can add Distributed-System informations to
> `Distributed.md` from ZhaoLong Li . This is an important content
> that we still lack, it will be helpful for us.
> 
> Thanks.

太多并且比较高深
我认为先看完6.824的的推荐论文，md已经发过你

**Pull request merged**
